### PR TITLE
Fix GFM table; typos; whitespace

### PR DESCRIPTION
**Pull request by richardkmichael**
✨

### CODE REVIEW

**Comment by pjb7687** [comment]
Thank you!

**Comment by richardkmichael** [comment]
@pjb7687 You're welcome, thank you for CAS-OFFinder!  May I ask a question here?  On the [online version](http://www.rgenome.net/cas-offinder/), DNA/RNA bulge can be set-- how to do that when running the stand-alone binary on my computer?  Thank you!

**Comment by pjb7687** [comment]
@richardkmichael We are using a small wrapper script for Cas-OFFinder, which can be found here: https://github.com/hyugel/cas-offinder-bulge

**Comment by richardkmichael** [comment]
@pjb7687 Thank you very much!

**Pull request merged**
