### PR TITLE
Adjust CMakeLists.txt to use cmake targets with module imports

### PR DESCRIPTION
**Pull request by richardkmichael**
Fixes missing OpenMP during linking on macOS 10.14.

### CODE REVIEW

**Comment by richardkmichael** [comment]
@pjb7687 

This will be the last PR I will send against the `master` branch, I only wanted to fix compiling on macOS.

Will you remove the `master` branch and change the repo default branch to `develop`?

**Comment by pjb7687** [comment]
> @pjb7687
> 
> This will be the last PR I will send against the `master` branch, I only wanted to fix compiling on macOS.
> 
> Will you remove the `master` branch and change the repo default branch to `develop`?

Nope, I am going to keep them both

**Comment by pjb7687** [comment]
I think this is basically the same as the one that included in PR merged to develop right? Then I think it is okay to keep master as it is.... I will merge the changes in develop branch to master after 3.0.0 release

**Comment by richardkmichael** [comment]
> I think this is basically the same as the one that included in PR merged to develop right? Then I think it is okay to keep master as it is.... I will merge the changes in develop branch to master after 3.0.0 release

It's the minimal changes required to compile with OpenMP, so a small subset of what's on develop.  But if you merge develop to master, then yes, this is unnecessary.  I will close this!

Why keep both branches?  This is a quite a small project, you could do releases with tags only.

If you intend to maintain a production/stable branches, separate from a development branch, I would rename master to `2.4.x` and also create a `3.0.x` branch when it is released.

Regardless, I would make `develop` the default branch.  Otherwise I think contributors will send PRs against `master`, if it remains the default branch (because most GitHub repos use `master` as their development branch, and it is also their repo default).

**Comment by pjb7687** [comment]
makes sense, I will do that after merging

**Comment by pjb7687** [comment]
Turned out I am too lazy to manage several release branches I just changed the default branch to `develop` and just changed the name of the master branch to `release`. Anyway it seems to be better.

**Comment by richardkmichael** [comment]
Definitely understandable! :)

Also, I agree it is better to have branches named for their purpose.  It was never obvious to me what function `master` branch was serving many projects.  It seems like a stable release name, but most projects use it for development.

**Pull request closed without merging**
