### PR TITLE
Rewrite

### PR DESCRIPTION
**Pull request by benblack769**

### CODE REVIEW

**Comment by pjb7687** [comment]
Hi, thanks for the PR, any explanations? However, unfortunately, I think I can't accept such a huge rewrite anyway.

**Comment by pjb7687** [comment]
Could you provide any justification for the rewrite? Is it faster?

**Comment by benblack769** [comment]
Yes, it isn't fully compatable, it is basically a full rewrite, and there are other reasons not to accept it, but it is much faster.

I wrote up a description of all the major optimizations here https://benblack769.github.io/posts/blog/cas-offinder/

I mostly wrote this because I wanted to practice some of my C++ skills (I've been working almost exclusively in python for a few years) while working on something kind of cool.

**Comment by benblack769** [comment]
My contributions start here https://benblack769.github.io/posts/blog/cas-offinder/#a-bitpacked-data-structure

The most notable thing about the perforamance is that even without a "pattern" (the second line of the input file), it can still search through a hundred compare strings on a full genome in <10 seconds on a decent GPU.

**Comment by pjb7687** [comment]
> My contributions start here https://benblack769.github.io/posts/blog/cas-offinder/#a-bitpacked-data-structure
> 

That's pretty neat! I learned a lot from your approach. I think I cannot merge this as is, but I consider doing that after I understand all of the changes you made, and also rigorous testing. Thanks a lot!

**Comment by benblack769** [comment]
Glad you learned something! I thought that this bit packing approach was quite neat as well.

**Comment by pjb7687** [comment]
> The most notable thing about the perforamance is that even without a "pattern" (the second line of the input file), it can still search through a hundred compare strings on a full genome in <10 seconds on a decent GPU.

That's great. One of the major bottlenecks without the "pattern" is storage. As Cas-OFFinder writes the results to a file if you save everything allowing many mismatches/bulges it will quickly fill up your whole drive space. Another thing is the slow I/O speed while writing such a big file, but it is nice to see that you have sort of worked on async I/O anyway.

Anyway, I think this will significantly speed up the bulge-allowed search, since it internally generates lots of compare strings. Super cool!

**Comment by benblack769** [comment]
Ok, I will close this for now and reopen when it is closer to being ready.

**Pull request closed without merging**
