### PR TITLE
Rewrite

### PR DESCRIPTION
**Pull request by benblack769**
Reopening this PR, as it now seems to be feature eqivalent:

To compile:

```
mkdir -p build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release && make -j4
```

This generates a few executables:

* cas-offinder-2: A executable compliant with the current 2.4.1 release of cas-offinder
* cas-offinder-2-nocl: Like cas-offinder-2, but with no dependency on opencl (CPU only)
* cas-offinder-3: A executable compliant with the 3.0.0b release of cas-offinder 
* cas-offinder-3-nocl: Like cas-offinder-3, but with no dependency on opencl (CPU only)
* test: unit tests for development

To run unit tests:

```
./build/test
```

```
# download data from ucsc genome repository (may take a few minutes)
python test/download.py
# compare output of cas-offinder release 2.4 against current build on specified input and device. Outputs diff, if any. Should not be any diff
python test/compare_impls.py test/example1.in G
# compare output of cas-offinder release 3.0.0b against current build on specified input and device. Will be a diff, however, I have inspected the output and it seems that this rewrite is more accurate for the most part.
python test/compare_impls3.py test/examplebulge.in G
```

As for performance, on my dual RTX 2060 setup, the `test/example1.in` runs in 2.5s in the new version vs 8s on the old. With v3 on the ` test/examplebulge.in` input, the new version runs in 7s for the new version vs 57s on the old. The memory utilization of the new version is consisitently under 700MB on the CPU and on the opencl device.

It also seems to perform quite well on other GPU types. On the intel integrated graphics on my laptop, example1.in runs in 5.24996 and examplebulge.in runs in 186.612s.

The opencl versions don't perform as well on CPU, but the -nocl executables perform reasonably well.

Let me know if there is anything else I can help out with.

### CODE REVIEW

**Comment by benblack769** [comment]
@pjb7687 Can you approve the workflow, so I can check it compiles on windows?

**Comment by pjb7687** [comment]
How about a complete rewriting using a better language natively supports async funcs e.g. Rust? I seriously consider that.

**Comment by pjb7687** [comment]
Just started an empty repo: https://github.com/pnucolab/cas-offinder-rust
I aim to push an initial commit soon if I make some progress

**Comment by benblack769** [comment]
The main performance benefit of this rewrite on large, complex inputs is not the async computation, but the better bit-packed data format. 

If you want to see some simpler more serial code, I am sure I can greatly simplify the current code and remove a lot of the fancy headers and such.

**Comment by benblack769** [comment]
Just ran a benchmark of the current code vs the cas-offinder 2.4.1 release on random guides on the human genome. Just pushed the code that runs the benchmark to `test/benchmark.py`

Device | Num Guides | Mismatches | PAM | Guide Length |  new code | cas-offinder 2.4.1
--- | --- | --- | --- | --- | --- | ---
G | 1 | 3 | NRG | 20 | **2.457066535949707** | 7.838363885879517
G | 1 | 3 | NRG | 25 | **2.5289411544799805** | 16.501859664916992
G | 1 | 3 | NNGRRT | 20 | **2.5530526638031006** | 6.3273797035217285
G | 1 | 3 | NNGRRT | 25 | **2.277801036834717** | 6.427332639694214
G | 1 | 3 | TTTN | 20 | **2.2968239784240723** | 14.080754280090332
G | 1 | 3 | TTTN | 25 | **2.269219160079956** | 17.261003017425537
G | 1 | 3 | NNN | 20 | **2.5658657550811768** | 9.768653869628906
G | 1 | 3 | NNN | 25 | **2.4853222370147705** | 27.38359498977661
G | 1 | 6 | NRG | 20 | **2.288862466812134** | 8.168041229248047
G | 1 | 6 | NRG | 25 | **2.296704053878784** | 17.12664294242859
G | 1 | 6 | NNGRRT | 20 | **2.3106417655944824** | 6.413571119308472
G | 1 | 6 | NNGRRT | 25 | **2.2874395847320557** | 6.45048189163208
G | 1 | 6 | TTTN | 20 | **2.597984790802002** | 15.61670446395874
G | 1 | 6 | TTTN | 25 | **2.301694869995117** | 16.070722341537476
G | 1 | 6 | NNN | 20 | **2.313948631286621** | 11.06814956665039
G | 1 | 6 | NNN | 25 | **2.546156406402588** | 32.08479380607605
G | 100 | 3 | NRG | 20 | **3.281158685684204** | 81.62353587150574
G | 100 | 3 | NRG | 25 | **4.345930576324463** | 106.61158084869385
G | 100 | 3 | NNGRRT | 20 | **4.305038928985596** | 14.771099328994751
G | 100 | 3 | NNGRRT | 25 | **4.255571126937866** | 15.478232860565186
G | 100 | 3 | TTTN | 20 | **3.267700433731079** | 41.72032713890076
G | 100 | 3 | TTTN | 25 | **4.387739181518555** | 46.10689091682434
G | 100 | 3 | NNN | 20 | **3.3470168113708496** | 255.67016053199768
G | 100 | 3 | NNN | 25 | **4.296769380569458** | 1038.861836194992
G | 100 | 6 | NRG | 20 | **7.8972320556640625** | 117.8295590877533
G | 100 | 6 | NRG | 25 | **4.395631313323975** | 142.38549041748047
G | 100 | 6 | NNGRRT | 20 | **7.213689565658569** | 18.794063568115234
G | 100 | 6 | NNGRRT | 25 | **4.371814727783203** | 20.25647521018982
G | 100 | 6 | TTTN | 20 | **6.948397159576416** | 53.07967925071716
G | 100 | 6 | TTTN | 25 | **4.3952319622039795** | 56.78704071044922
G | 100 | 6 | NNN | 20 | **20.577077388763428** | 379.30489897727966
G | 100 | 6 | NNN | 25 | **4.327762842178345** | 1509.7268223762512
C | 1 | 3 | NRG | 20 | **3.590397834777832** | 43.46000361442566
C | 1 | 3 | NRG | 25 | **3.6751527786254883** | 43.74400877952576
C | 1 | 3 | NNGRRT | 20 | **3.6508681774139404** | 13.540801286697388
C | 1 | 3 | NNGRRT | 25 | **3.632962703704834** | 12.931318521499634
C | 1 | 3 | TTTN | 20 | **3.759443998336792** | 20.997319221496582
C | 1 | 3 | TTTN | 25 | **3.628269910812378** | 21.615241765975952
C | 1 | 3 | NNN | 20 | **3.641589641571045** | 157.16770362854004
C | 1 | 3 | NNN | 25 | **3.554177761077881** | 157.28540921211243
C | 1 | 6 | NRG | 20 | **3.6152164936065674** | 45.03748655319214
C | 1 | 6 | NRG | 25 | **3.5648601055145264** | 43.65849947929382
C | 1 | 6 | NNGRRT | 20 | **3.6128592491149902** | 13.665508031845093
C | 1 | 6 | NNGRRT | 25 | **3.7108068466186523** | 12.900066137313843
C | 1 | 6 | TTTN | 20 | **3.6672797203063965** | 21.239816188812256
C | 1 | 6 | TTTN | 25 | **3.5897068977355957** | 22.04256582260132
C | 1 | 6 | NNN | 20 | **3.665330648422241** | 164.93094301223755
C | 1 | 6 | NNN | 25 | **3.700547933578491** | 164.99052476882935
C | 100 | 3 | NRG | 20 | 195.8663148880005 | **191.26478362083435**
C | 100 | 3 | NRG | 25 | **198.46067905426025** | 201.00600957870483
C | 100 | 3 | NNGRRT | 20 | 197.7969355583191 | **39.44978475570679**
C | 100 | 3 | NNGRRT | 25 | 197.9326527118683 | **38.36330270767212**
C | 100 | 3 | TTTN | 20 | 197.84042501449585 | **68.67597556114197**
C | 100 | 3 | TTTN | 25 | 198.83449029922485 | **73.39102458953857**
C | 100 | 3 | NNN | 20 | **199.13335537910461** | 1149.2943522930145

**Comment by pjb7687** [comment]
> The main performance benefit of this rewrite on large, complex inputs is not the async computation, but the better bit-packed data format.
> 
> If you want to see some simpler more serial code, I am sure I can greatly simplify the current code and remove a lot of the fancy headers and such.

I understand your point, but it doesn't mean your fancy things, incl. async, iteration, file i/o, are not useful. I just suggest that perhaps it can be more easily achieved by migrating to a more modern language that supports such features natively. We don't have to reinvent the wheel.

**Comment by benblack769** [comment]
Sorry for the late reply. 

I am not very familiar with Rust, and I don't have the capacity to learn the language right now. However, I tried to test this implementation at multiple levels to make sure it gives the same or better results than the current version, so I think it is good as is. Let me know if there is anything I can clean up in this current rewrite.

**Comment by benblack769** [comment]
@pjb7687 Perhaps, rather than a full rewrite, this change would be more acceptable if I simply modify the existing code to use this 4 bit encoding and search method?

If that would be more acceptable, then let me know which branch I should base off of (develop or release).

**Comment by pjb7687** [comment]
Hi @benblack769, Sorry for the late response, I've been super busy these days. I just wrote an email to you - please check it out. Thanks!

**Pull request closed without merging**
